HW1: Setup
Alexander-Zadorozhnyy/formal-lang-course pull request #1
Opened 2023-09-13 12:39 UTC by Alexander-Zadorozhnyy

- Added graph utils
- Added tests
- Added workflow for testing

2023-09-13 17:58 UTC, vadyushkins requested changes

2023-09-13 17:58 UTC, vadyushkins commented on .github/workflows/testing.yaml
> +name: Check code style
?

2023-09-13 17:58 UTC, vadyushkins commented on .github/workflows/testing.yaml
> +    runs-on: ubuntu-latest
windows, macos

2023-09-13 17:58 UTC, vadyushkins commented on project/cfpq/graph_worker.py
> +from networkx import Graph
MultiDiGraph

2023-09-13 17:58 UTC, vadyushkins commented on project/cfpq/graph_worker.py
> +    print(gw.get_graph_info())
?

2023-09-13 17:58 UTC, vadyushkins commented on project/cfpq/main.py
> +    create_and_save_two_cycles_graph((5, "a"), (5, "b"), "test.dot")
?

2023-09-14 15:16 UTC, Alexander-Zadorozhnyy commented on project/cfpq/main.py
> +    create_and_save_two_cycles_graph((5, "a"), (5, "b"), "test.dot")
Здравствуйте, Вадим! Ревью все также нужно, последний commit окончательный. Все вернул к изначальному состоянию, до всех изменений с pydot и graphviz (проблема описана в группе telegram).

2023-09-15 19:21 UTC, vadyushkins approved these changes

2023-09-16 15:53 UTC, merged